### ISSUE TITLE
Feedback#1 presentation and doc

### ISSUE THREAD

**Issue by BoSott** [hnzlmnn/fossgis-project#1]
presentation and Latex document are well done, concise and to the point.

Just as a recommendation for the next review submission, please provide an .odt and / or a .pdf document since not everybody is able to work with Latex documents.

**Comment by AnjaDo** [comment]
Hi, thanks for the feedback - and yes good point. 
If you are referring to the Latex doc - write-up - this is still a work in process and therefore also not meant to be explicitly accessible (just yet). 
We can however provide you with a pdf of the presentation document, that could of course be useful and accessible for everyone.

**Comment by hnzlmnn** [comment]
Added the PDF in 807b231
