### ISSUE TITLE
Feedback#2 requirements

### ISSUE THREAD

**Issue by BoSott** [hnzlmnn/fossgis-project#2]
Please provide a requirements document and some sort of setup guide for the environment.

**Comment by hnzlmnn** [comment]
As stated in the Readme within the demo folder, you should be able to run the code without any other dependencies than the OSGeo4W `py3_env`. If you are on Linux/Mac, you have have GDAL installed as described in the Seminar. If you still have any issues running the code, please attach the error message.

**Comment by BoSott** [comment]
In my experience it is just common for a project like this, to have the requirements, installation guideline, setup and an example how to run it all in the first README in the root folder. Just to make it as easy as possible for others to get it running. Switching through different folders to find answers is just cumbersome IMHO. Why did you do it this way? (I guess you had a good reason :) )

The README in "Code" was additionally just not really understandable for us as there is no context given. For sure it makes sense to one who knows the project well, but for us who are new to it, it doesn't provide enough information.

"you have have GDAL installed as described in the Seminar." it would be great if you would provide this information here, as this shall be a stand-alone project.

**Comment by hnzlmnn** [comment]
The README for the demo belongs to the demo. The repository contains everything I didn't want to have multiple repositories. The three folders should be considered separate. The environment should use Python3 with GDAL available. There are no other requirements. As GDAL cannot be installed through pip, there is no requirements.txt or Pipfile.

**Comment by BoSott** [comment]
okay, just tried to give constructive feedback. These were the main points we struggled with. You can of course do as you wish :) if you have a python environment (python -m venv venv) you can install gdal via pip

Secondly, closing an issue without waiting for an answer is in my experience considered bad practise.

**Comment by hnzlmnn** [comment]
All feedback is welcomed :)

Apparently for non-Windows you **can** install GDAL through [pip](https://pypi.org/project/GDAL/). However, on Windows we recommend using [OSGeo4W](https://www.osgeo.org/projects/osgeo4w/) and then activating the python 3 environment within the OSGeo4W Shell using `py3_env`.

I thought the issue "lack of setup instructions" was answered with my comments, thus closing the issue seemed logical.

**Comment by hnzlmnn** [comment]
If you feel, the issue still exists, feel free to re-open the issue ;)

**Comment by BoSott** [comment]
Cool! :) this (some more detailed instructions) in your README would probably do the trick. Got the demo to run on Ubuntu 20.04. Have a good week!
