### ISSUE TITLE
Feedback#4 runtime / results

### ISSUE THREAD

**Issue by BoSott** [hnzlmnn/fossgis-project#4]
Unfortunately, no one in our group got the setup right to run the demo.py, nor the actual code, so we can't say much about it. We tried it on Win, Ubuntu and ArchLinux but your results in the presentation were good, so we assume it does what it's supposed to do :)

**Comment by AnjaDo** [comment]
Oh that is unfortunate... you should of course be able to run it. 
Could you state a bit more in detail what you tried to do?

Did you try with entering > python3 demo.py < ?

**Comment by hnzlmnn** [comment]
As commented in #2 please ensure, the GDAL Python 3 environment is correctly setup in the shell you are starting `demo.py` from.

**Comment by BoSott** [comment]
Thanks for your answers. It would be great if you could provide a complete and detailed setup guide here (requirements, installation [environment], setup) as it is as important as the project itself and just using a different GDAL version than you might already kill the project on our side..

**Comment by hnzlmnn** [comment]
Added in 72152d5. There should be no special requirement to any version of GDAL. On how to setup GDAL, please follow the instructions in the GDAL [documentation](https://gdal.org/index.html) and make sure you are using Python3. If you are still unable to run the project please re-open the issue with the error message that you are getting.
